version: "3.8"

services:

  ckan-web:
    image: saeoss:latest
    ports:
      - target: 5000
        published: 5000
    volumes:
      - type: bind
        source: $PWD
        target: /home/appuser/app
      - type: bind
        source: $PWD/docker/ckan-dev-settings.ini
        target: /home/appuser/ckan.ini
      - type: bind
        source: $PWD/docker/who.ini
        target: /home/appuser/who.ini
      - ckan-storage:/home/appuser/data

  ckan-db:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_USER: ckan-dev
      POSTGRES_PASSWORD: ckan-dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - target: 5432
        published: 55432
    volumes:
      - ckan-db-data:/var/lib/postgresql/data
    command: ["-clog_statement=all"]

  solr:
    image: ckan/ckan-solr:2.9-solr8-spatial
    ports:
      - target: 8983
        published: 8983
    volumes:
      - type: bind
        source: $PWD/docker/solr/schema.xml
        target: /opt/solr/server/solr/ckan/conf/schema.xml
      - solr-data:/opt/solr/server/solr/ckan/data

  redis:
    image: redis:6.2

volumes:
  solr-data:
  ckan-storage:
  ckan-db-data: