site_name: SAWPS
site_description: "SANBI WPS technical and user documentation."
site_author: "Kartoza"
docs_dir: ./src
site_dir: ./site
repo_name: "SANBI WPS"
repo_url: "https://github.com/kartoza/sawps/"
edit_uri: "https://github.com/kartoza/sawps/blob/main/docs/"

copyright: Kartoza and Contributors

markdown_extensions:
        - pymdownx.highlight:
                  anchor_linenums: true
        - pymdownx.inlinehilite
        #- mdx_truly_sane_lists
        - toc:
                  permalink: true
                   #slugify: !!python/name:pymdownx.slugs.slugify
        - pymdownx.snippets:
                  base_path: .
        - admonition
        - tables
        - pymdownx.details
        - pymdownx.caret
        - pymdownx.keys
        - pymdownx.mark
        - pymdownx.tilde
        - pymdownx.superfences:
                  custom_fences:
                          - name: mermaid
                            class: mermaid
                            format: !!python/name:pymdownx.superfences.fence_code_format
        - pymdownx.emoji:
                  emoji_generator: !!python/name:materialx.emoji.to_svg
                  emoji_index: !!python/name:materialx.emoji.twemoji

nav:
        - Home:
                  - Home: index.md
                  - License: license.md
        - User:
                  - Quickstart: user/quickstart.md
                  - Instructions: user/instructions.md
                  - User Roles: user/permissions.md
        - Admin:
                  - Admin: admin/index.md
        - Developer:
                  - Developer: developer/index.md
                  - Narrative: developer/narrative.md
                  - Code Auto docs: developer/code_auto_docs.md
                  - Contribution Guidelines: developer/contribution_guidelines.md
                  - How to make docs: developer/make_docs.md
                  - Design: developer/design.md
                  - How to run instances: developer/run_instances.md
                  - How to test local instance: developer/test_local.md
                  - License: license.md



        - DevOps:
                  - DevOps: devops/index.md
        - About:
                  - About: about/index.md
                  - License: about/license.md
                  - Contributors: about/contributors.md
                  - Funders: about/funders.md
                  - Logos: about/logos.md

# Configuration
theme:
  name: material
  logo: img/SANBI-logo.jpg
  language: en
  direction: ltr
  include_search_page: false
  search_index_only: true
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    primary: custom
#    - scheme: default
#      primary: custom
#      accent: custom
#      toggle:
#        icon: material/brightness-4
#        name: Switch to dark mode
#    - scheme: slate
#      primary: custom
#      accent: custom
#      toggle:
#        icon: material/brightness-6
#        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  icon:
    logo: material/book

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kartoza
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/kartoza/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KartozaGeo
    - icon: fontawesome/brands/facebook
      link: https://kartoza.com
    - icon: fontawesome/solid/earth-africa
      link: https://kartoza.com

extra_css:
  - css/extra.css
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js

plugins:
  - search
